'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace ServiceSupport
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceSupport.ServiceSupportSoap")>  _
    Public Interface ServiceSupportSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/LoginSupport", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function LoginSupport(ByVal username As String, ByVal password As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/LoginSupport", ReplyAction:="*")>  _
        Function LoginSupportAsync(ByVal username As String, ByVal password As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CustomerLogList", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function CustomerLogList(ByVal username As String, ByVal filter As String, ByVal type As String, ByVal custnum As String, ByVal submittedDate As Date, ByVal stat As String, ByVal suptype As String, ByVal req As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/CustomerLogList", ReplyAction:="*")>  _
        Function CustomerLogListAsync(ByVal username As String, ByVal filter As String, ByVal type As String, ByVal custnum As String, ByVal submittedDate As Date, ByVal stat As String, ByVal suptype As String, ByVal req As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/LogDetail", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function LogDetail(ByVal log_id As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/LogDetail", ReplyAction:="*")>  _
        Function LogDetailAsync(ByVal log_id As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetCustomer", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetCustomer(ByVal sCustGroup As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetCustomer", ReplyAction:="*")>  _
        Function GetCustomerAsync(ByVal sCustGroup As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SignupSupport", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function SignupSupport(ByVal username As String, ByVal password As String, ByVal customer As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SignupSupport", ReplyAction:="*")>  _
        Function SignupSupportAsync(ByVal username As String, ByVal password As String, ByVal customer As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetStatusSupport", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetStatusSupport() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetStatusSupport", ReplyAction:="*")>  _
        Function GetStatusSupportAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetTypeSupport", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetTypeSupport() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetTypeSupport", ReplyAction:="*")>  _
        Function GetTypeSupportAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetRequestorSupport", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetRequestorSupport(ByVal customer As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetRequestorSupport", ReplyAction:="*")>  _
        Function GetRequestorSupportAsync(ByVal customer As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetSupportLogReport", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetSupportLogReport(ByVal StartCust As String, ByVal EndCust As String, ByVal StartReqDate As Date, ByVal EndReqDate As Date, ByVal Open As Integer, ByVal Inprocess As Integer, ByVal Close As Integer, ByVal CustGroup As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetSupportLogReport", ReplyAction:="*")>  _
        Function GetSupportLogReportAsync(ByVal StartCust As String, ByVal EndCust As String, ByVal StartReqDate As Date, ByVal EndReqDate As Date, ByVal Open As Integer, ByVal Inprocess As Integer, ByVal Close As Integer, ByVal CustGroup As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InsertSupportLog", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function InsertSupportLog( _
                    ByVal LogID As String,  _
                    ByVal Stat As String,  _
                    ByVal CustNum As String,  _
                    ByVal DBSite As String,  _
                    ByVal FormName As String,  _
                    ByVal Subject As String,  _
                    ByVal Problem As String,  _
                    ByVal Attachment As String,  _
                    ByVal Email As String,  _
                    ByVal Requestor As String,  _
                    ByVal sModule As String,  _
                    ByVal sSeverity As String,  _
                    ByVal sProgramGroup As String,  _
                    ByVal dProjectDate As Date,  _
                    ByVal dRequestDate As Date,  _
                    ByVal iAfterWork As Integer,  _
                    ByVal iHoliday As Integer,  _
                    ByVal sInform As String,  _
                    ByVal sCause As String,  _
                    ByVal sHowtoCheck As String,  _
                    ByVal sCurrentSol As String,  _
                    ByVal sLongTermSol As String,  _
                    ByVal sRequestTime As String,  _
                    ByVal sAcknowledgeBy As String,  _
                    ByVal dResponseDate As Date,  _
                    ByVal sResponseTime As String,  _
                    ByVal User As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InsertSupportLog", ReplyAction:="*")>  _
        Function InsertSupportLogAsync( _
                    ByVal LogID As String,  _
                    ByVal Stat As String,  _
                    ByVal CustNum As String,  _
                    ByVal DBSite As String,  _
                    ByVal FormName As String,  _
                    ByVal Subject As String,  _
                    ByVal Problem As String,  _
                    ByVal Attachment As String,  _
                    ByVal Email As String,  _
                    ByVal Requestor As String,  _
                    ByVal sModule As String,  _
                    ByVal sSeverity As String,  _
                    ByVal sProgramGroup As String,  _
                    ByVal dProjectDate As Date,  _
                    ByVal dRequestDate As Date,  _
                    ByVal iAfterWork As Integer,  _
                    ByVal iHoliday As Integer,  _
                    ByVal sInform As String,  _
                    ByVal sCause As String,  _
                    ByVal sHowtoCheck As String,  _
                    ByVal sCurrentSol As String,  _
                    ByVal sLongTermSol As String,  _
                    ByVal sRequestTime As String,  _
                    ByVal sAcknowledgeBy As String,  _
                    ByVal dResponseDate As Date,  _
                    ByVal sResponseTime As String,  _
                    ByVal User As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetDatabaseSite", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetDatabaseSite(ByVal CustNum As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetDatabaseSite", ReplyAction:="*")>  _
        Function GetDatabaseSiteAsync(ByVal CustNum As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetEmailRequestor", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetEmailRequestor(ByVal CustNum As String, ByVal Req As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetEmailRequestor", ReplyAction:="*")>  _
        Function GetEmailRequestorAsync(ByVal CustNum As String, ByVal Req As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetResource", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetResource() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetResource", ReplyAction:="*")>  _
        Function GetResourceAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetErrorType", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetErrorType() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetErrorType", ReplyAction:="*")>  _
        Function GetErrorTypeAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/UpdateSupportLog", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function UpdateSupportLog( _
                    ByVal LogId As String,  _
                    ByVal Stat As String,  _
                    ByVal Cause As String,  _
                    ByVal Solution As String,  _
                    ByVal ErrorType As String,  _
                    ByVal Responsible As String,  _
                    ByVal ClosedBy As String,  _
                    ByVal Problem As String,  _
                    ByVal User As String,  _
                    ByVal HowtoCheck As String,  _
                    ByVal CurrentSol As String,  _
                    ByVal LongTermSol As String,  _
                    ByVal RespondDate As Date,  _
                    ByVal RespondTime As String,  _
                    ByVal EndDate As Date,  _
                    ByVal EndTime As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/UpdateSupportLog", ReplyAction:="*")>  _
        Function UpdateSupportLogAsync( _
                    ByVal LogId As String,  _
                    ByVal Stat As String,  _
                    ByVal Cause As String,  _
                    ByVal Solution As String,  _
                    ByVal ErrorType As String,  _
                    ByVal Responsible As String,  _
                    ByVal ClosedBy As String,  _
                    ByVal Problem As String,  _
                    ByVal User As String,  _
                    ByVal HowtoCheck As String,  _
                    ByVal CurrentSol As String,  _
                    ByVal LongTermSol As String,  _
                    ByVal RespondDate As Date,  _
                    ByVal RespondTime As String,  _
                    ByVal EndDate As Date,  _
                    ByVal EndTime As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetSupportModule", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetSupportModule() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetSupportModule", ReplyAction:="*")>  _
        Function GetSupportModuleAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetRequestor", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetRequestor(ByVal CustNum As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetRequestor", ReplyAction:="*")>  _
        Function GetRequestorAsync(ByVal CustNum As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InsertRequestor", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function InsertRequestor(ByVal Company As String, ByVal Req As String, ByVal FirstName As String, ByVal LastName As String, ByVal Email As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InsertRequestor", ReplyAction:="*")>  _
        Function InsertRequestorAsync(ByVal Company As String, ByVal Req As String, ByVal FirstName As String, ByVal LastName As String, ByVal Email As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InsertReplyLog", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function InsertReplyLog(ByVal LogId As String, ByVal Reply As String, ByVal Username As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InsertReplyLog", ReplyAction:="*")>  _
        Function InsertReplyLogAsync(ByVal LogId As String, ByVal Reply As String, ByVal Username As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetReplyLog", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetReplyLog(ByVal LogId As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetReplyLog", ReplyAction:="*")>  _
        Function GetReplyLogAsync(ByVal LogId As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetIssueSummaryReport", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetIssueSummaryReport(ByVal StartCust As String, ByVal EndCust As String, ByVal StartReqDate As Date, ByVal EndReqDate As Date, ByVal CustGroup As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetIssueSummaryReport", ReplyAction:="*")>  _
        Function GetIssueSummaryReportAsync(ByVal StartCust As String, ByVal EndCust As String, ByVal StartReqDate As Date, ByVal EndReqDate As Date, ByVal CustGroup As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetIssueSummaryReports", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetIssueSummaryReports(ByVal StartCust As String, ByVal EndCust As String, ByVal StartReqDate As Date, ByVal EndReqDate As Date, ByVal CustGroup As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetIssueSummaryReports", ReplyAction:="*")>  _
        Function GetIssueSummaryReportsAsync(ByVal StartCust As String, ByVal EndCust As String, ByVal StartReqDate As Date, ByVal EndReqDate As Date, ByVal CustGroup As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetUserWebSupport", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetUserWebSupport() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetUserWebSupport", ReplyAction:="*")>  _
        Function GetUserWebSupportAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InsertUserWebSupport", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function InsertUserWebSupport(ByVal sUsername As String, ByVal sPassword As String, ByVal sCustomer As String, ByVal sCategory As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/InsertUserWebSupport", ReplyAction:="*")>  _
        Function InsertUserWebSupportAsync(ByVal sUsername As String, ByVal sPassword As String, ByVal sCustomer As String, ByVal sCategory As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/UpdateUserWebSupport", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function UpdateUserWebSupport(ByVal sUsername As String, ByVal sPassword As String, ByVal sCustomer As String, ByVal sCategory As String, ByVal sRowPointer As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/UpdateUserWebSupport", ReplyAction:="*")>  _
        Function UpdateUserWebSupportAsync(ByVal sUsername As String, ByVal sPassword As String, ByVal sCustomer As String, ByVal sCategory As String, ByVal sRowPointer As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/DeleteUserWebSupport", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function DeleteUserWebSupport(ByVal sRowPointer As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/DeleteUserWebSupport", ReplyAction:="*")>  _
        Function DeleteUserWebSupportAsync(ByVal sRowPointer As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/UpdateRequestor", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function UpdateRequestor(ByVal sReq As String, ByVal sName As String, ByVal sLastName As String, ByVal sEmail As String, ByVal sCustomer As String, ByVal sRowPointer As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/UpdateRequestor", ReplyAction:="*")>  _
        Function UpdateRequestorAsync(ByVal sReq As String, ByVal sName As String, ByVal sLastName As String, ByVal sEmail As String, ByVal sCustomer As String, ByVal sRowPointer As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/DeleteRequestor", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function DeleteRequestor(ByVal sRowPointer As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/DeleteRequestor", ReplyAction:="*")>  _
        Function DeleteRequestorAsync(ByVal sRowPointer As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetSeverity", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetSeverity() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetSeverity", ReplyAction:="*")>  _
        Function GetSeverityAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetProgramGroup", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetProgramGroup(ByVal sModule As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetProgramGroup", ReplyAction:="*")>  _
        Function GetProgramGroupAsync(ByVal sModule As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetProjectedDate", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetProjectedDate(ByVal sCurrDate As Date, ByVal iSeverity As Integer, ByVal sShift As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetProjectedDate", ReplyAction:="*")>  _
        Function GetProjectedDateAsync(ByVal sCurrDate As Date, ByVal iSeverity As Integer, ByVal sShift As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetCustomerEmailSupport", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetCustomerEmailSupport(ByVal sCustNum As String) As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetCustomerEmailSupport", ReplyAction:="*")>  _
        Function GetCustomerEmailSupportAsync(ByVal sCustNum As String) As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetInformProblem", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetInformProblem() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetInformProblem", ReplyAction:="*")>  _
        Function GetInformProblemAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetResponse", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults:=true)>  _
        Function GetResponse() As System.Data.DataTable
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetResponse", ReplyAction:="*")>  _
        Function GetResponseAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ServiceSupportSoapChannel
        Inherits ServiceSupport.ServiceSupportSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ServiceSupportSoapClient
        Inherits System.ServiceModel.ClientBase(Of ServiceSupport.ServiceSupportSoap)
        Implements ServiceSupport.ServiceSupportSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function LoginSupport(ByVal username As String, ByVal password As String) As System.Data.DataTable Implements ServiceSupport.ServiceSupportSoap.LoginSupport
            Return MyBase.Channel.LoginSupport(username, password)
        End Function
        
        Public Function LoginSupportAsync(ByVal username As String, ByVal password As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements ServiceSupport.ServiceSupportSoap.LoginSupportAsync
            Return MyBase.Channel.LoginSupportAsync(username, password)
        End Function
        
        Public Function CustomerLogList(ByVal username As String, ByVal filter As String, ByVal type As String, ByVal custnum As String, ByVal submittedDate As Date, ByVal stat As String, ByVal suptype As String, ByVal req As String) As System.Data.DataTable Implements ServiceSupport.ServiceSupportSoap.CustomerLogList
            Return MyBase.Channel.CustomerLogList(username, filter, type, custnum, submittedDate, stat, suptype, req)
        End Function
        
        Public Function CustomerLogListAsync(ByVal username As String, ByVal filter As String, ByVal type As String, ByVal custnum As String, ByVal submittedDate As Date, ByVal stat As String, ByVal suptype As String, ByVal req As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements ServiceSupport.ServiceSupportSoap.CustomerLogListAsync
            Return MyBase.Channel.CustomerLogListAsync(username, filter, type, custnum, submittedDate, stat, suptype, req)
        End Function
        
        Public Function LogDetail(ByVal log_id As String) As System.Data.DataTable Implements ServiceSupport.ServiceSupportSoap.LogDetail
            Return MyBase.Channel.LogDetail(log_id)
        End Function
        
        Public Function LogDetailAsync(ByVal log_id As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements ServiceSupport.ServiceSupportSoap.LogDetailAsync
            Return MyBase.Channel.LogDetailAsync(log_id)
        End Function
        
        Public Function GetCustomer(ByVal sCustGroup As String) As System.Data.DataTable Implements ServiceSupport.ServiceSupportSoap.GetCustomer
            Return MyBase.Channel.GetCustomer(sCustGroup)
        End Function
        
        Public Function GetCustomerAsync(ByVal sCustGroup As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements ServiceSupport.ServiceSupportSoap.GetCustomerAsync
            Return MyBase.Channel.GetCustomerAsync(sCustGroup)
        End Function
        
        Public Function SignupSupport(ByVal username As String, ByVal password As String, ByVal customer As String) As System.Data.DataTable Implements ServiceSupport.ServiceSupportSoap.SignupSupport
            Return MyBase.Channel.SignupSupport(username, password, customer)
        End Function
        
        Public Function SignupSupportAsync(ByVal username As String, ByVal password As String, ByVal customer As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements ServiceSupport.ServiceSupportSoap.SignupSupportAsync
            Return MyBase.Channel.SignupSupportAsync(username, password, customer)
        End Function
        
        Public Function GetStatusSupport() As System.Data.DataTable Implements ServiceSupport.ServiceSupportSoap.GetStatusSupport
            Return MyBase.Channel.GetStatusSupport
        End Function
        
        Public Function GetStatusSupportAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements ServiceSupport.ServiceSupportSoap.GetStatusSupportAsync
            Return MyBase.Channel.GetStatusSupportAsync
        End Function
        
        Public Function GetTypeSupport() As System.Data.DataTable Implements ServiceSupport.ServiceSupportSoap.GetTypeSupport
            Return MyBase.Channel.GetTypeSupport
        End Function
        
        Public Function GetTypeSupportAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements ServiceSupport.ServiceSupportSoap.GetTypeSupportAsync
            Return MyBase.Channel.GetTypeSupportAsync
        End Function
        
        Public Function GetRequestorSupport(ByVal customer As String) As System.Data.DataTable Implements ServiceSupport.ServiceSupportSoap.GetRequestorSupport
            Return MyBase.Channel.GetRequestorSupport(customer)
        End Function
        
        Public Function GetRequestorSupportAsync(ByVal customer As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements ServiceSupport.ServiceSupportSoap.GetRequestorSupportAsync
            Return MyBase.Channel.GetRequestorSupportAsync(customer)
        End Function
        
        Public Function GetSupportLogReport(ByVal StartCust As String, ByVal EndCust As String, ByVal StartReqDate As Date, ByVal EndReqDate As Date, ByVal Open As Integer, ByVal Inprocess As Integer, ByVal Close As Integer, ByVal CustGroup As String) As System.Data.DataTable Implements ServiceSupport.ServiceSupportSoap.GetSupportLogReport
            Return MyBase.Channel.GetSupportLogReport(StartCust, EndCust, StartReqDate, EndReqDate, Open, Inprocess, Close, CustGroup)
        End Function
        
        Public Function GetSupportLogReportAsync(ByVal StartCust As String, ByVal EndCust As String, ByVal StartReqDate As Date, ByVal EndReqDate As Date, ByVal Open As Integer, ByVal Inprocess As Integer, ByVal Close As Integer, ByVal CustGroup As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements ServiceSupport.ServiceSupportSoap.GetSupportLogReportAsync
            Return MyBase.Channel.GetSupportLogReportAsync(StartCust, EndCust, StartReqDate, EndReqDate, Open, Inprocess, Close, CustGroup)
        End Function
        
        Public Function InsertSupportLog( _
                    ByVal LogID As String,  _
                    ByVal Stat As String,  _
                    ByVal CustNum As String,  _
                    ByVal DBSite As String,  _
                    ByVal FormName As String,  _
                    ByVal Subject As String,  _
                    ByVal Problem As String,  _
                    ByVal Attachment As String,  _
                    ByVal Email As String,  _
                    ByVal Requestor As String,  _
                    ByVal sModule As String,  _
                    ByVal sSeverity As String,  _
                    ByVal sProgramGroup As String,  _
                    ByVal dProjectDate As Date,  _
                    ByVal dRequestDate As Date,  _
                    ByVal iAfterWork As Integer,  _
                    ByVal iHoliday As Integer,  _
                    ByVal sInform As String,  _
                    ByVal sCause As String,  _
                    ByVal sHowtoCheck As String,  _
                    ByVal sCurrentSol As String,  _
                    ByVal sLongTermSol As String,  _
                    ByVal sRequestTime As String,  _
                    ByVal sAcknowledgeBy As String,  _
                    ByVal dResponseDate As Date,  _
                    ByVal sResponseTime As String,  _
                    ByVal User As String) As System.Data.DataTable Implements ServiceSupport.ServiceSupportSoap.InsertSupportLog
            Return MyBase.Channel.InsertSupportLog(LogID, Stat, CustNum, DBSite, FormName, Subject, Problem, Attachment, Email, Requestor, sModule, sSeverity, sProgramGroup, dProjectDate, dRequestDate, iAfterWork, iHoliday, sInform, sCause, sHowtoCheck, sCurrentSol, sLongTermSol, sRequestTime, sAcknowledgeBy, dResponseDate, sResponseTime, User)
        End Function
        
        Public Function InsertSupportLogAsync( _
                    ByVal LogID As String,  _
                    ByVal Stat As String,  _
                    ByVal CustNum As String,  _
                    ByVal DBSite As String,  _
                    ByVal FormName As String,  _
                    ByVal Subject As String,  _
                    ByVal Problem As String,  _
                    ByVal Attachment As String,  _
                    ByVal Email As String,  _
                    ByVal Requestor As String,  _
                    ByVal sModule As String,  _
                    ByVal sSeverity As String,  _
                    ByVal sProgramGroup As String,  _
                    ByVal dProjectDate As Date,  _
                    ByVal dRequestDate As Date,  _
                    ByVal iAfterWork As Integer,  _
                    ByVal iHoliday As Integer,  _
                    ByVal sInform As String,  _
                    ByVal sCause As String,  _
                    ByVal sHowtoCheck As String,  _
                    ByVal sCurrentSol As String,  _
                    ByVal sLongTermSol As String,  _
                    ByVal sRequestTime As String,  _
                    ByVal sAcknowledgeBy As String,  _
                    ByVal dResponseDate As Date,  _
                    ByVal sResponseTime As String,  _
                    ByVal User As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements ServiceSupport.ServiceSupportSoap.InsertSupportLogAsync
            Return MyBase.Channel.InsertSupportLogAsync(LogID, Stat, CustNum, DBSite, FormName, Subject, Problem, Attachment, Email, Requestor, sModule, sSeverity, sProgramGroup, dProjectDate, dRequestDate, iAfterWork, iHoliday, sInform, sCause, sHowtoCheck, sCurrentSol, sLongTermSol, sRequestTime, sAcknowledgeBy, dResponseDate, sResponseTime, User)
        End Function
        
        Public Function GetDatabaseSite(ByVal CustNum As String) As System.Data.DataTable Implements ServiceSupport.ServiceSupportSoap.GetDatabaseSite
            Return MyBase.Channel.GetDatabaseSite(CustNum)
        End Function
        
        Public Function GetDatabaseSiteAsync(ByVal CustNum As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements ServiceSupport.ServiceSupportSoap.GetDatabaseSiteAsync
            Return MyBase.Channel.GetDatabaseSiteAsync(CustNum)
        End Function
        
        Public Function GetEmailRequestor(ByVal CustNum As String, ByVal Req As String) As System.Data.DataTable Implements ServiceSupport.ServiceSupportSoap.GetEmailRequestor
            Return MyBase.Channel.GetEmailRequestor(CustNum, Req)
        End Function
        
        Public Function GetEmailRequestorAsync(ByVal CustNum As String, ByVal Req As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements ServiceSupport.ServiceSupportSoap.GetEmailRequestorAsync
            Return MyBase.Channel.GetEmailRequestorAsync(CustNum, Req)
        End Function
        
        Public Function GetResource() As System.Data.DataTable Implements ServiceSupport.ServiceSupportSoap.GetResource
            Return MyBase.Channel.GetResource
        End Function
        
        Public Function GetResourceAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements ServiceSupport.ServiceSupportSoap.GetResourceAsync
            Return MyBase.Channel.GetResourceAsync
        End Function
        
        Public Function GetErrorType() As System.Data.DataTable Implements ServiceSupport.ServiceSupportSoap.GetErrorType
            Return MyBase.Channel.GetErrorType
        End Function
        
        Public Function GetErrorTypeAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements ServiceSupport.ServiceSupportSoap.GetErrorTypeAsync
            Return MyBase.Channel.GetErrorTypeAsync
        End Function
        
        Public Function UpdateSupportLog( _
                    ByVal LogId As String,  _
                    ByVal Stat As String,  _
                    ByVal Cause As String,  _
                    ByVal Solution As String,  _
                    ByVal ErrorType As String,  _
                    ByVal Responsible As String,  _
                    ByVal ClosedBy As String,  _
                    ByVal Problem As String,  _
                    ByVal User As String,  _
                    ByVal HowtoCheck As String,  _
                    ByVal CurrentSol As String,  _
                    ByVal LongTermSol As String,  _
                    ByVal RespondDate As Date,  _
                    ByVal RespondTime As String,  _
                    ByVal EndDate As Date,  _
                    ByVal EndTime As String) As System.Data.DataTable Implements ServiceSupport.ServiceSupportSoap.UpdateSupportLog
            Return MyBase.Channel.UpdateSupportLog(LogId, Stat, Cause, Solution, ErrorType, Responsible, ClosedBy, Problem, User, HowtoCheck, CurrentSol, LongTermSol, RespondDate, RespondTime, EndDate, EndTime)
        End Function
        
        Public Function UpdateSupportLogAsync( _
                    ByVal LogId As String,  _
                    ByVal Stat As String,  _
                    ByVal Cause As String,  _
                    ByVal Solution As String,  _
                    ByVal ErrorType As String,  _
                    ByVal Responsible As String,  _
                    ByVal ClosedBy As String,  _
                    ByVal Problem As String,  _
                    ByVal User As String,  _
                    ByVal HowtoCheck As String,  _
                    ByVal CurrentSol As String,  _
                    ByVal LongTermSol As String,  _
                    ByVal RespondDate As Date,  _
                    ByVal RespondTime As String,  _
                    ByVal EndDate As Date,  _
                    ByVal EndTime As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements ServiceSupport.ServiceSupportSoap.UpdateSupportLogAsync
            Return MyBase.Channel.UpdateSupportLogAsync(LogId, Stat, Cause, Solution, ErrorType, Responsible, ClosedBy, Problem, User, HowtoCheck, CurrentSol, LongTermSol, RespondDate, RespondTime, EndDate, EndTime)
        End Function
        
        Public Function GetSupportModule() As System.Data.DataTable Implements ServiceSupport.ServiceSupportSoap.GetSupportModule
            Return MyBase.Channel.GetSupportModule
        End Function
        
        Public Function GetSupportModuleAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements ServiceSupport.ServiceSupportSoap.GetSupportModuleAsync
            Return MyBase.Channel.GetSupportModuleAsync
        End Function
        
        Public Function GetRequestor(ByVal CustNum As String) As System.Data.DataTable Implements ServiceSupport.ServiceSupportSoap.GetRequestor
            Return MyBase.Channel.GetRequestor(CustNum)
        End Function
        
        Public Function GetRequestorAsync(ByVal CustNum As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements ServiceSupport.ServiceSupportSoap.GetRequestorAsync
            Return MyBase.Channel.GetRequestorAsync(CustNum)
        End Function
        
        Public Function InsertRequestor(ByVal Company As String, ByVal Req As String, ByVal FirstName As String, ByVal LastName As String, ByVal Email As String) As System.Data.DataTable Implements ServiceSupport.ServiceSupportSoap.InsertRequestor
            Return MyBase.Channel.InsertRequestor(Company, Req, FirstName, LastName, Email)
        End Function
        
        Public Function InsertRequestorAsync(ByVal Company As String, ByVal Req As String, ByVal FirstName As String, ByVal LastName As String, ByVal Email As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements ServiceSupport.ServiceSupportSoap.InsertRequestorAsync
            Return MyBase.Channel.InsertRequestorAsync(Company, Req, FirstName, LastName, Email)
        End Function
        
        Public Function InsertReplyLog(ByVal LogId As String, ByVal Reply As String, ByVal Username As String) As System.Data.DataTable Implements ServiceSupport.ServiceSupportSoap.InsertReplyLog
            Return MyBase.Channel.InsertReplyLog(LogId, Reply, Username)
        End Function
        
        Public Function InsertReplyLogAsync(ByVal LogId As String, ByVal Reply As String, ByVal Username As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements ServiceSupport.ServiceSupportSoap.InsertReplyLogAsync
            Return MyBase.Channel.InsertReplyLogAsync(LogId, Reply, Username)
        End Function
        
        Public Function GetReplyLog(ByVal LogId As String) As System.Data.DataTable Implements ServiceSupport.ServiceSupportSoap.GetReplyLog
            Return MyBase.Channel.GetReplyLog(LogId)
        End Function
        
        Public Function GetReplyLogAsync(ByVal LogId As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements ServiceSupport.ServiceSupportSoap.GetReplyLogAsync
            Return MyBase.Channel.GetReplyLogAsync(LogId)
        End Function
        
        Public Function GetIssueSummaryReport(ByVal StartCust As String, ByVal EndCust As String, ByVal StartReqDate As Date, ByVal EndReqDate As Date, ByVal CustGroup As String) As System.Data.DataTable Implements ServiceSupport.ServiceSupportSoap.GetIssueSummaryReport
            Return MyBase.Channel.GetIssueSummaryReport(StartCust, EndCust, StartReqDate, EndReqDate, CustGroup)
        End Function
        
        Public Function GetIssueSummaryReportAsync(ByVal StartCust As String, ByVal EndCust As String, ByVal StartReqDate As Date, ByVal EndReqDate As Date, ByVal CustGroup As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements ServiceSupport.ServiceSupportSoap.GetIssueSummaryReportAsync
            Return MyBase.Channel.GetIssueSummaryReportAsync(StartCust, EndCust, StartReqDate, EndReqDate, CustGroup)
        End Function
        
        Public Function GetIssueSummaryReports(ByVal StartCust As String, ByVal EndCust As String, ByVal StartReqDate As Date, ByVal EndReqDate As Date, ByVal CustGroup As String) As System.Data.DataTable Implements ServiceSupport.ServiceSupportSoap.GetIssueSummaryReports
            Return MyBase.Channel.GetIssueSummaryReports(StartCust, EndCust, StartReqDate, EndReqDate, CustGroup)
        End Function
        
        Public Function GetIssueSummaryReportsAsync(ByVal StartCust As String, ByVal EndCust As String, ByVal StartReqDate As Date, ByVal EndReqDate As Date, ByVal CustGroup As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements ServiceSupport.ServiceSupportSoap.GetIssueSummaryReportsAsync
            Return MyBase.Channel.GetIssueSummaryReportsAsync(StartCust, EndCust, StartReqDate, EndReqDate, CustGroup)
        End Function
        
        Public Function GetUserWebSupport() As System.Data.DataTable Implements ServiceSupport.ServiceSupportSoap.GetUserWebSupport
            Return MyBase.Channel.GetUserWebSupport
        End Function
        
        Public Function GetUserWebSupportAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements ServiceSupport.ServiceSupportSoap.GetUserWebSupportAsync
            Return MyBase.Channel.GetUserWebSupportAsync
        End Function
        
        Public Function InsertUserWebSupport(ByVal sUsername As String, ByVal sPassword As String, ByVal sCustomer As String, ByVal sCategory As String) As System.Data.DataTable Implements ServiceSupport.ServiceSupportSoap.InsertUserWebSupport
            Return MyBase.Channel.InsertUserWebSupport(sUsername, sPassword, sCustomer, sCategory)
        End Function
        
        Public Function InsertUserWebSupportAsync(ByVal sUsername As String, ByVal sPassword As String, ByVal sCustomer As String, ByVal sCategory As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements ServiceSupport.ServiceSupportSoap.InsertUserWebSupportAsync
            Return MyBase.Channel.InsertUserWebSupportAsync(sUsername, sPassword, sCustomer, sCategory)
        End Function
        
        Public Function UpdateUserWebSupport(ByVal sUsername As String, ByVal sPassword As String, ByVal sCustomer As String, ByVal sCategory As String, ByVal sRowPointer As String) As System.Data.DataTable Implements ServiceSupport.ServiceSupportSoap.UpdateUserWebSupport
            Return MyBase.Channel.UpdateUserWebSupport(sUsername, sPassword, sCustomer, sCategory, sRowPointer)
        End Function
        
        Public Function UpdateUserWebSupportAsync(ByVal sUsername As String, ByVal sPassword As String, ByVal sCustomer As String, ByVal sCategory As String, ByVal sRowPointer As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements ServiceSupport.ServiceSupportSoap.UpdateUserWebSupportAsync
            Return MyBase.Channel.UpdateUserWebSupportAsync(sUsername, sPassword, sCustomer, sCategory, sRowPointer)
        End Function
        
        Public Function DeleteUserWebSupport(ByVal sRowPointer As String) As System.Data.DataTable Implements ServiceSupport.ServiceSupportSoap.DeleteUserWebSupport
            Return MyBase.Channel.DeleteUserWebSupport(sRowPointer)
        End Function
        
        Public Function DeleteUserWebSupportAsync(ByVal sRowPointer As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements ServiceSupport.ServiceSupportSoap.DeleteUserWebSupportAsync
            Return MyBase.Channel.DeleteUserWebSupportAsync(sRowPointer)
        End Function
        
        Public Function UpdateRequestor(ByVal sReq As String, ByVal sName As String, ByVal sLastName As String, ByVal sEmail As String, ByVal sCustomer As String, ByVal sRowPointer As String) As System.Data.DataTable Implements ServiceSupport.ServiceSupportSoap.UpdateRequestor
            Return MyBase.Channel.UpdateRequestor(sReq, sName, sLastName, sEmail, sCustomer, sRowPointer)
        End Function
        
        Public Function UpdateRequestorAsync(ByVal sReq As String, ByVal sName As String, ByVal sLastName As String, ByVal sEmail As String, ByVal sCustomer As String, ByVal sRowPointer As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements ServiceSupport.ServiceSupportSoap.UpdateRequestorAsync
            Return MyBase.Channel.UpdateRequestorAsync(sReq, sName, sLastName, sEmail, sCustomer, sRowPointer)
        End Function
        
        Public Function DeleteRequestor(ByVal sRowPointer As String) As System.Data.DataTable Implements ServiceSupport.ServiceSupportSoap.DeleteRequestor
            Return MyBase.Channel.DeleteRequestor(sRowPointer)
        End Function
        
        Public Function DeleteRequestorAsync(ByVal sRowPointer As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements ServiceSupport.ServiceSupportSoap.DeleteRequestorAsync
            Return MyBase.Channel.DeleteRequestorAsync(sRowPointer)
        End Function
        
        Public Function GetSeverity() As System.Data.DataTable Implements ServiceSupport.ServiceSupportSoap.GetSeverity
            Return MyBase.Channel.GetSeverity
        End Function
        
        Public Function GetSeverityAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements ServiceSupport.ServiceSupportSoap.GetSeverityAsync
            Return MyBase.Channel.GetSeverityAsync
        End Function
        
        Public Function GetProgramGroup(ByVal sModule As String) As System.Data.DataTable Implements ServiceSupport.ServiceSupportSoap.GetProgramGroup
            Return MyBase.Channel.GetProgramGroup(sModule)
        End Function
        
        Public Function GetProgramGroupAsync(ByVal sModule As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements ServiceSupport.ServiceSupportSoap.GetProgramGroupAsync
            Return MyBase.Channel.GetProgramGroupAsync(sModule)
        End Function
        
        Public Function GetProjectedDate(ByVal sCurrDate As Date, ByVal iSeverity As Integer, ByVal sShift As String) As System.Data.DataTable Implements ServiceSupport.ServiceSupportSoap.GetProjectedDate
            Return MyBase.Channel.GetProjectedDate(sCurrDate, iSeverity, sShift)
        End Function
        
        Public Function GetProjectedDateAsync(ByVal sCurrDate As Date, ByVal iSeverity As Integer, ByVal sShift As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements ServiceSupport.ServiceSupportSoap.GetProjectedDateAsync
            Return MyBase.Channel.GetProjectedDateAsync(sCurrDate, iSeverity, sShift)
        End Function
        
        Public Function GetCustomerEmailSupport(ByVal sCustNum As String) As System.Data.DataTable Implements ServiceSupport.ServiceSupportSoap.GetCustomerEmailSupport
            Return MyBase.Channel.GetCustomerEmailSupport(sCustNum)
        End Function
        
        Public Function GetCustomerEmailSupportAsync(ByVal sCustNum As String) As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements ServiceSupport.ServiceSupportSoap.GetCustomerEmailSupportAsync
            Return MyBase.Channel.GetCustomerEmailSupportAsync(sCustNum)
        End Function
        
        Public Function GetInformProblem() As System.Data.DataTable Implements ServiceSupport.ServiceSupportSoap.GetInformProblem
            Return MyBase.Channel.GetInformProblem
        End Function
        
        Public Function GetInformProblemAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements ServiceSupport.ServiceSupportSoap.GetInformProblemAsync
            Return MyBase.Channel.GetInformProblemAsync
        End Function
        
        Public Function GetResponse() As System.Data.DataTable Implements ServiceSupport.ServiceSupportSoap.GetResponse
            Return MyBase.Channel.GetResponse
        End Function
        
        Public Function GetResponseAsync() As System.Threading.Tasks.Task(Of System.Data.DataTable) Implements ServiceSupport.ServiceSupportSoap.GetResponseAsync
            Return MyBase.Channel.GetResponseAsync
        End Function
    End Class
End Namespace
