'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class OldUpdateSupportLog
    
    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager
    
    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''NotPassNotifyPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NotPassNotifyPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''NotPassText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NotPassText As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''PassNotifyPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PassNotifyPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''PassText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PassText As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lblLogID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLogID As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtLogID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLogID As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStatus As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlStat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlStat As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblCustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustomer As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlCustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCustomer As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblSubject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubject As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtSubject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSubject As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lnkDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkDetails As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lblProblems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProblems As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtProblems control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProblems As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblCause control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCause As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtCause control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCause As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblSolution control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSolution As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtSolution control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSolution As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblHowtoCheck control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHowtoCheck As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtHowtoCheck control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtHowtoCheck As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblCurrentSol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrentSol As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtCurrentSol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCurrentSol As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblLongTermSol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLongTermSol As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtLongTermSol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLongTermSol As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblErrorType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorType As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlErrorType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlErrorType As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblResponsible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblResponsible As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlResponsible control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlResponsible As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblResponseDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblResponseDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtResponseDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtResponseDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblResponseTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblResponseTime As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlResponseTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlResponseTime As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblClosedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClosedBy As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlClosedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlClosedBy As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblClosedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClosedDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtClosedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClosedDate As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblClosedTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClosedTime As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlClosedTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlClosedTime As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblLogId1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLogId1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''slblLogId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents slblLogId As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCust control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCust As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''slblCust control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents slblCust As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblRequestor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRequestor As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''slblRequestor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents slblRequestor As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblReqDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReqDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''slblReqDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents slblReqDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblFormName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFormName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''slblFormName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents slblFormName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblDbSite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDbSite As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''slblDbSite control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents slblDbSite As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblProblem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProblem As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''slblProblem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents slblProblem As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCauses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCauses As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''slblCauses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents slblCauses As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSolutions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSolutions As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''slblSolutions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents slblSolutions As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblResponseBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblResponseBy As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''slblResponseBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents slblResponseBy As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCloseDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCloseDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''slblCloseDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents slblCloseDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblCloseBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCloseBy As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''slblCloseBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents slblCloseBy As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button
End Class
